"""Unit tests for backpropagate/ui_workdir.py (v1.8.2 per-user UI workdir).

The stub-render tests use the REAL shipped rxconfig.py as the template, so
they double as a drift tripwire: if the package template drops or duplicates
the ``app_module_import="ui_app.app"`` anchor, this module fails before the
CLI ever would.
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

import pytest

from backpropagate import __version__, ui_workdir
from backpropagate.exceptions import BackpropagateError
from backpropagate.ui_workdir import (
    WORKDIR_ENV_VAR,
    default_ui_work_root,
    ensure_ui_workdir,
    package_dir_key,
    package_dir_writable,
    prepare_ui_cwd,
)

PACKAGE_DIR = Path(ui_workdir.__file__).resolve().parent


@pytest.fixture
def default_env(monkeypatch, tmp_path):
    """Exercise DEFAULT resolution: undo the conftest autouse override and
    pin the platform cache roots under tmp_path."""
    monkeypatch.delenv(WORKDIR_ENV_VAR, raising=False)
    monkeypatch.setenv("LOCALAPPDATA", str(tmp_path / "local-appdata"))
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path / "xdg-cache"))
    return monkeypatch


class TestPackageDirKey:
    def test_stable_8_lowercase_hex(self):
        key = package_dir_key(PACKAGE_DIR)
        assert len(key) == 8
        assert key == key.lower()
        int(key, 16)
        assert package_dir_key(PACKAGE_DIR) == key

    def test_distinct_install_dirs_get_distinct_keys(self, tmp_path):
        other = tmp_path / "elsewhere" / "backpropagate"
        other.mkdir(parents=True)
        assert package_dir_key(other) != package_dir_key(PACKAGE_DIR)


class TestDefaultRoot:
    def test_honours_platform_cache_env(self, default_env, tmp_path):
        root = default_ui_work_root()
        if sys.platform == "win32":
            assert root == tmp_path / "local-appdata" / "backpropagate" / "ui"
        else:
            assert root == tmp_path / "xdg-cache" / "backpropagate" / "ui"

    def test_falls_back_to_profile_defaults(self, default_env):
        default_env.delenv("XDG_CACHE_HOME", raising=False)
        default_env.delenv("LOCALAPPDATA", raising=False)
        root = default_ui_work_root()
        if sys.platform == "win32":
            assert root == Path.home() / "AppData" / "Local" / "backpropagate" / "ui"
        else:
            assert root == Path.home() / ".cache" / "backpropagate" / "ui"


class TestEnsureWorkdir:
    def test_versioned_layout_and_stub_contents(self, default_env):
        wd = ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        assert wd == default_ui_work_root() / f"9.9.9-{package_dir_key(PACKAGE_DIR)}"
        stub = (wd / "rxconfig.py").read_text(encoding="utf-8")
        assert stub.startswith("# GENERATED by backpropagate")
        assert 'app_module_import="backpropagate.ui_app.app"' in stub
        assert 'app_module_import="ui_app.app"' not in stub
        # The template's load-bearing settings survive the copy verbatim.
        assert "telemetry_enabled=False" in stub
        assert "_any_ui_auth_env" in stub
        assert "FRONTEND-B-001" in stub

    def test_installed_version_used_by_default(self, default_env):
        wd = ensure_ui_workdir(PACKAGE_DIR)
        assert wd.name == f"{__version__}-{package_dir_key(PACKAGE_DIR)}"

    def test_stub_not_rewritten_when_current(self, default_env):
        wd = ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        stub_path = wd / "rxconfig.py"
        first_mtime = stub_path.stat().st_mtime_ns
        wd2 = ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        assert wd2 == wd
        assert stub_path.stat().st_mtime_ns == first_mtime

    def test_stub_regenerated_after_tamper(self, default_env):
        wd = ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        stub_path = wd / "rxconfig.py"
        stub_path.write_text("garbage", encoding="utf-8")
        ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        assert "garbage" not in stub_path.read_text(encoding="utf-8")

    def test_prunes_only_stale_same_install_dirs(self, default_env):
        key = package_dir_key(PACKAGE_DIR)
        base = default_ui_work_root()
        stale_same_install = base / f"1.8.1-{key}"
        other_install = base / "1.8.1-deadbeef"
        hashless_dir = base / "1.8.1"
        unrelated_file = base / "keep.me"
        for d in (stale_same_install, other_install, hashless_dir):
            d.mkdir(parents=True)
            (d / "sentinel.txt").write_text("x", encoding="utf-8")
        unrelated_file.parent.mkdir(parents=True, exist_ok=True)
        unrelated_file.write_text("x", encoding="utf-8")

        wd = ensure_ui_workdir(PACKAGE_DIR, version="1.8.2")

        assert not stale_same_install.exists()
        assert wd.name == f"1.8.2-{key}" and wd.is_dir()
        for survivor in (other_install, hashless_dir, unrelated_file):
            assert survivor.exists(), f"pruning must not touch {survivor}"

    def test_prune_failure_warns_and_continues(self, default_env, monkeypatch):
        key = package_dir_key(PACKAGE_DIR)
        stale = default_ui_work_root() / f"1.8.1-{key}"
        stale.mkdir(parents=True)

        def deny(path, *a, **k):
            raise OSError("directory locked")

        monkeypatch.setattr(shutil, "rmtree", deny)
        messages: list[str] = []
        wd = ensure_ui_workdir(PACKAGE_DIR, version="1.8.2", warn=messages.append)
        assert wd.is_dir()
        assert stale.exists()
        assert any("stale UI working directory" in m for m in messages)


class TestEnvOverride:
    def test_override_used_verbatim(self, monkeypatch, tmp_path):
        target = tmp_path / "custom" / "wherever"
        monkeypatch.setenv(WORKDIR_ENV_VAR, str(target))
        wd = ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        assert wd == target
        assert (wd / "rxconfig.py").is_file()

    def test_override_skips_sibling_pruning(self, monkeypatch, tmp_path, default_env):
        # An override inside the default base with a same-key stale sibling:
        # override mode must not prune anything.
        key = package_dir_key(PACKAGE_DIR)
        stale = default_ui_work_root() / f"1.8.1-{key}"
        stale.mkdir(parents=True)
        override = default_ui_work_root() / "pinned"
        monkeypatch.setenv(WORKDIR_ENV_VAR, str(override))
        assert ensure_ui_workdir(PACKAGE_DIR) == override
        assert stale.exists()


class TestTemplateDrift:
    def test_shipped_template_has_exactly_one_anchor(self):
        text = (PACKAGE_DIR / "rxconfig.py").read_text(encoding="utf-8")
        assert text.count('app_module_import="ui_app.app"') == 1

    def test_drifted_template_raises_loudly(self, monkeypatch, tmp_path):
        fake_pkg = tmp_path / "pkg"
        fake_pkg.mkdir()
        (fake_pkg / "rxconfig.py").write_text(
            "import reflex as rx\nconfig = rx.Config(app_name='x')\n",
            encoding="utf-8",
        )
        monkeypatch.setenv(WORKDIR_ENV_VAR, str(tmp_path / "wd"))
        with pytest.raises(RuntimeError, match="anchor"):
            ensure_ui_workdir(fake_pkg)


class TestUiAssets:
    """The UI's images (logo, icons) must reach the working directory.

    Regression (1.8.2 dev): once Reflex ran from the per-user workdir, the
    package's ``assets/`` stayed behind, so every ``/logo.png`` and
    ``/icons/*.svg`` request was a 404 and the UI showed broken images.
    """

    def test_default_workdir_gets_the_real_assets(self, default_env):
        wd = ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        shipped = sorted(p.relative_to(PACKAGE_DIR / "assets") for p in (PACKAGE_DIR / "assets").rglob("*") if p.is_file())
        copied = sorted(p.relative_to(wd / "assets") for p in (wd / "assets").rglob("*") if p.is_file())
        assert shipped, "the package should ship UI assets"
        assert copied == shipped
        assert (wd / "assets" / "logo.png").read_bytes() == (PACKAGE_DIR / "assets" / "logo.png").read_bytes()

    def test_override_workdir_gets_assets(self, monkeypatch, tmp_path):
        target = tmp_path / "custom-ui"
        monkeypatch.setenv(WORKDIR_ENV_VAR, str(target))
        wd = ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        assert (wd / "assets" / "logo.png").is_file()

    def test_changed_asset_is_refreshed_and_unchanged_is_left(self, tmp_path):
        pkg = tmp_path / "pkg"
        (pkg / "assets" / "icons").mkdir(parents=True)
        (pkg / "assets" / "logo.png").write_bytes(b"v1")
        (pkg / "assets" / "icons" / "a.svg").write_bytes(b"<svg/>")
        wd = tmp_path / "wd"
        ui_workdir.sync_ui_assets(pkg, wd)
        assert (wd / "assets" / "logo.png").read_bytes() == b"v1"
        before = (wd / "assets" / "icons" / "a.svg").stat().st_mtime_ns

        (pkg / "assets" / "logo.png").write_bytes(b"version-two")
        ui_workdir.sync_ui_assets(pkg, wd)
        assert (wd / "assets" / "logo.png").read_bytes() == b"version-two"
        assert (wd / "assets" / "icons" / "a.svg").stat().st_mtime_ns == before

    def test_package_without_assets_is_fine(self, tmp_path):
        ui_workdir.sync_ui_assets(tmp_path / "no-assets-pkg", tmp_path / "wd")
        assert not (tmp_path / "wd" / "assets").exists()


def _forbid_package_writes(monkeypatch, pkg: Path) -> None:
    """Raise if a write path is aimed at ``pkg`` or anything inside it."""
    root = pkg.resolve()

    def banned(path: Path) -> None:
        try:
            resolved = Path(path).resolve()
        except OSError:
            resolved = Path(path)
        if resolved == root or root in resolved.parents:
            raise AssertionError(f"write attempted in the package folder: {resolved}")

    real_mkdir = Path.mkdir
    real_write_text = Path.write_text
    real_write_bytes = Path.write_bytes
    real_copy2 = shutil.copy2

    def mkdir(self, *args, **kwargs):
        banned(self)
        return real_mkdir(self, *args, **kwargs)

    def write_text(self, *args, **kwargs):
        banned(self)
        return real_write_text(self, *args, **kwargs)

    def write_bytes(self, *args, **kwargs):
        banned(self)
        return real_write_bytes(self, *args, **kwargs)

    def copy2(src, dst, *args, **kwargs):
        banned(Path(dst))
        return real_copy2(src, dst, *args, **kwargs)

    monkeypatch.setattr(Path, "mkdir", mkdir)
    monkeypatch.setattr(Path, "write_text", write_text)
    monkeypatch.setattr(Path, "write_bytes", write_bytes)
    monkeypatch.setattr(shutil, "copy2", copy2)


def _deny_package_write_access(monkeypatch, pkg: Path) -> None:
    real_access = os.access

    def access(path, mode, *args, **kwargs):
        try:
            if Path(path).resolve() == pkg.resolve() and mode & os.W_OK:
                return False
        except OSError:
            pass
        return real_access(path, mode, *args, **kwargs)

    monkeypatch.setattr(ui_workdir.os, "access", access)


class TestReadOnlyPackage:
    def test_uncreatable_user_dir_and_readonly_package_errors_without_writing(
        self, monkeypatch, tmp_path
    ):
        monkeypatch.delenv(WORKDIR_ENV_VAR, raising=False)
        pkg = tmp_path / "pkg"
        pkg.mkdir()
        (pkg / "rxconfig.py").write_text("template-bytes", encoding="utf-8")
        (pkg / "assets").mkdir()
        (pkg / "assets" / "logo.png").write_bytes(b"png")
        before = {
            p.relative_to(pkg): p.read_bytes() for p in pkg.rglob("*") if p.is_file()
        }
        blocker = tmp_path / "localappdata"
        blocker.write_text("not-a-directory", encoding="utf-8")
        # Both platform roots, so the per-user folder is blocked on Windows
        # (LOCALAPPDATA) and on Linux / macOS (XDG_CACHE_HOME) alike.
        monkeypatch.setenv("LOCALAPPDATA", str(blocker))
        monkeypatch.setenv("XDG_CACHE_HOME", str(blocker))
        _deny_package_write_access(monkeypatch, pkg)
        _forbid_package_writes(monkeypatch, pkg)

        with pytest.raises(BackpropagateError) as exc:
            prepare_ui_cwd(pkg, version="1.8.2")

        err = exc.value
        assert err.code == "RUNTIME_UI_WORKDIR_UNAVAILABLE"
        assert str(blocker) in err.message
        assert "BACKPROPAGATE_UI_WORKDIR" in (err.suggestion or "")
        after = {
            p.relative_to(pkg): p.read_bytes() for p in pkg.rglob("*") if p.is_file()
        }
        assert after == before

    def test_writable_checkout_falls_back_without_rewriting_the_template(
        self, monkeypatch, tmp_path
    ):
        monkeypatch.delenv(WORKDIR_ENV_VAR, raising=False)
        pkg = tmp_path / "pkg"
        pkg.mkdir()
        (pkg / "rxconfig.py").write_text("leave-me", encoding="utf-8")
        blocker = tmp_path / "localappdata"
        blocker.write_text("not-a-directory", encoding="utf-8")
        # Both platform roots, so the per-user folder is blocked on Windows
        # (LOCALAPPDATA) and on Linux / macOS (XDG_CACHE_HOME) alike.
        monkeypatch.setenv("LOCALAPPDATA", str(blocker))
        monkeypatch.setenv("XDG_CACHE_HOME", str(blocker))
        messages: list[str] = []

        got = prepare_ui_cwd(pkg, version="1.8.2", warn=messages.append)

        assert got == pkg
        assert (pkg / "rxconfig.py").read_text(encoding="utf-8") == "leave-me"
        assert any("package directory" in message for message in messages)
        assert any(str(blocker) in message for message in messages)

    def test_access_error_treats_the_package_as_not_writable(self, monkeypatch, tmp_path):
        def boom(*_a, **_k):
            raise OSError("acl")

        monkeypatch.setattr(ui_workdir.os, "access", boom)
        assert package_dir_writable(tmp_path) is False
