"""Unit tests for backpropagate/ui_workdir.py (v1.8.2 per-user UI workdir).

The stub-render tests use the REAL shipped rxconfig.py as the template, so
they double as a drift tripwire: if the package template drops or duplicates
the ``app_module_import="ui_app.app"`` anchor, this module fails before the
CLI ever would.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import pytest

from backpropagate import __version__, ui_workdir
from backpropagate.ui_workdir import (
    WORKDIR_ENV_VAR,
    default_ui_work_root,
    ensure_ui_workdir,
    package_dir_key,
)

PACKAGE_DIR = Path(ui_workdir.__file__).resolve().parent


@pytest.fixture
def default_env(monkeypatch, tmp_path):
    """Exercise DEFAULT resolution: undo the conftest autouse override and
    pin the platform cache roots under tmp_path."""
    monkeypatch.delenv(WORKDIR_ENV_VAR, raising=False)
    monkeypatch.setenv("LOCALAPPDATA", str(tmp_path / "local-appdata"))
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path / "xdg-cache"))
    return monkeypatch


class TestPackageDirKey:
    def test_stable_8_lowercase_hex(self):
        key = package_dir_key(PACKAGE_DIR)
        assert len(key) == 8
        assert key == key.lower()
        int(key, 16)
        assert package_dir_key(PACKAGE_DIR) == key

    def test_distinct_install_dirs_get_distinct_keys(self, tmp_path):
        other = tmp_path / "elsewhere" / "backpropagate"
        other.mkdir(parents=True)
        assert package_dir_key(other) != package_dir_key(PACKAGE_DIR)


class TestDefaultRoot:
    def test_honours_platform_cache_env(self, default_env, tmp_path):
        root = default_ui_work_root()
        if sys.platform == "win32":
            assert root == tmp_path / "local-appdata" / "backpropagate" / "ui"
        else:
            assert root == tmp_path / "xdg-cache" / "backpropagate" / "ui"

    def test_falls_back_to_profile_defaults(self, default_env):
        default_env.delenv("XDG_CACHE_HOME", raising=False)
        default_env.delenv("LOCALAPPDATA", raising=False)
        root = default_ui_work_root()
        if sys.platform == "win32":
            assert root == Path.home() / "AppData" / "Local" / "backpropagate" / "ui"
        else:
            assert root == Path.home() / ".cache" / "backpropagate" / "ui"


class TestEnsureWorkdir:
    def test_versioned_layout_and_stub_contents(self, default_env):
        wd = ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        assert wd == default_ui_work_root() / f"9.9.9-{package_dir_key(PACKAGE_DIR)}"
        stub = (wd / "rxconfig.py").read_text(encoding="utf-8")
        assert stub.startswith("# GENERATED by backpropagate")
        assert 'app_module_import="backpropagate.ui_app.app"' in stub
        assert 'app_module_import="ui_app.app"' not in stub
        # The template's load-bearing settings survive the copy verbatim.
        assert "telemetry_enabled=False" in stub
        assert "_any_ui_auth_env" in stub
        assert "FRONTEND-B-001" in stub

    def test_installed_version_used_by_default(self, default_env):
        wd = ensure_ui_workdir(PACKAGE_DIR)
        assert wd.name == f"{__version__}-{package_dir_key(PACKAGE_DIR)}"

    def test_stub_not_rewritten_when_current(self, default_env):
        wd = ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        stub_path = wd / "rxconfig.py"
        first_mtime = stub_path.stat().st_mtime_ns
        wd2 = ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        assert wd2 == wd
        assert stub_path.stat().st_mtime_ns == first_mtime

    def test_stub_regenerated_after_tamper(self, default_env):
        wd = ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        stub_path = wd / "rxconfig.py"
        stub_path.write_text("garbage", encoding="utf-8")
        ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        assert "garbage" not in stub_path.read_text(encoding="utf-8")

    def test_prunes_only_stale_same_install_dirs(self, default_env):
        key = package_dir_key(PACKAGE_DIR)
        base = default_ui_work_root()
        stale_same_install = base / f"1.8.1-{key}"
        other_install = base / "1.8.1-deadbeef"
        hashless_dir = base / "1.8.1"
        unrelated_file = base / "keep.me"
        for d in (stale_same_install, other_install, hashless_dir):
            d.mkdir(parents=True)
            (d / "sentinel.txt").write_text("x", encoding="utf-8")
        unrelated_file.parent.mkdir(parents=True, exist_ok=True)
        unrelated_file.write_text("x", encoding="utf-8")

        wd = ensure_ui_workdir(PACKAGE_DIR, version="1.8.2")

        assert not stale_same_install.exists()
        assert wd.name == f"1.8.2-{key}" and wd.is_dir()
        for survivor in (other_install, hashless_dir, unrelated_file):
            assert survivor.exists(), f"pruning must not touch {survivor}"

    def test_prune_failure_warns_and_continues(self, default_env, monkeypatch):
        key = package_dir_key(PACKAGE_DIR)
        stale = default_ui_work_root() / f"1.8.1-{key}"
        stale.mkdir(parents=True)

        def deny(path, *a, **k):
            raise OSError("directory locked")

        monkeypatch.setattr(shutil, "rmtree", deny)
        messages: list[str] = []
        wd = ensure_ui_workdir(PACKAGE_DIR, version="1.8.2", warn=messages.append)
        assert wd.is_dir()
        assert stale.exists()
        assert any("stale UI working directory" in m for m in messages)


class TestEnvOverride:
    def test_override_used_verbatim(self, monkeypatch, tmp_path):
        target = tmp_path / "custom" / "wherever"
        monkeypatch.setenv(WORKDIR_ENV_VAR, str(target))
        wd = ensure_ui_workdir(PACKAGE_DIR, version="9.9.9")
        assert wd == target
        assert (wd / "rxconfig.py").is_file()

    def test_override_skips_sibling_pruning(self, monkeypatch, tmp_path, default_env):
        # An override inside the default base with a same-key stale sibling:
        # override mode must not prune anything.
        key = package_dir_key(PACKAGE_DIR)
        stale = default_ui_work_root() / f"1.8.1-{key}"
        stale.mkdir(parents=True)
        override = default_ui_work_root() / "pinned"
        monkeypatch.setenv(WORKDIR_ENV_VAR, str(override))
        assert ensure_ui_workdir(PACKAGE_DIR) == override
        assert stale.exists()


class TestTemplateDrift:
    def test_shipped_template_has_exactly_one_anchor(self):
        text = (PACKAGE_DIR / "rxconfig.py").read_text(encoding="utf-8")
        assert text.count('app_module_import="ui_app.app"') == 1

    def test_drifted_template_raises_loudly(self, monkeypatch, tmp_path):
        fake_pkg = tmp_path / "pkg"
        fake_pkg.mkdir()
        (fake_pkg / "rxconfig.py").write_text(
            "import reflex as rx\nconfig = rx.Config(app_name='x')\n",
            encoding="utf-8",
        )
        monkeypatch.setenv(WORKDIR_ENV_VAR, str(tmp_path / "wd"))
        with pytest.raises(RuntimeError, match="anchor"):
            ensure_ui_workdir(fake_pkg)
