"""Per-user working directory for the Reflex UI (v1.8.2).

``reflex run`` writes its build + state tree (``.web/``, ``.states/``,
``reflex.lock/``, ``uploaded_files/``, ``requirements.txt``, ``.gitignore``)
into its cwd. Up to 1.8.1 the cwd was the installed package directory, which
breaks for read-only install locations — the Microsoft Store MSIX layout
(``C:\\Program Files\\WindowsApps\\...``) is the forcing case.

Since 1.8.2 ``cmd_ui`` runs Reflex from a per-user working directory::

    <base>/backpropagate/ui/<version>-<hash8>

``<base>`` is ``%LOCALAPPDATA%`` on Windows and the XDG cache dir
(``$XDG_CACHE_HOME``, default ``~/.cache``) elsewhere. ``<hash8>`` is the
first 8 hex chars of the SHA-256 of the normcased package directory, so a
pip install and a Store install (different package dirs) coexist, while a
pip upgrade in place (same package dir, new version) gets a fresh directory
and stale same-install directories are pruned on launch.

The working directory holds a stub ``rxconfig.py`` rendered from the
package-side template: byte-identical except ``app_module_import`` points at
the installed package (``backpropagate.ui_app.app``) instead of the
cwd-relative ``ui_app.app``. The stub therefore keeps the template's auth
refuse-to-start guard, CORS allowlist logic and ``telemetry_enabled=False``
automatically; if the template ever drops the anchor line the render fails
loudly instead of guessing.

Set ``BACKPROPAGATE_UI_WORKDIR`` to bypass all of the above: the value is
used verbatim as the working directory (no ``<version>-<hash8>`` suffix, no
sibling pruning). Tests and sandboxed launchers use this.

When that per-user folder cannot be created and the package directory is
not writable (the Store layout), :func:`prepare_ui_cwd` raises
``RUNTIME_UI_WORKDIR_UNAVAILABLE`` and does not write into the package.
A writable source checkout still falls back to the package directory so
``backprop ui`` can run from a checkout whose profile directory is blocked.
"""

from __future__ import annotations

import hashlib
import os
import shutil
import sys
from collections.abc import Callable
from pathlib import Path

WORKDIR_ENV_VAR = "BACKPROPAGATE_UI_WORKDIR"

_APP_MODULE_IMPORT_REL = 'app_module_import="ui_app.app"'
_APP_MODULE_IMPORT_ABS = 'app_module_import="backpropagate.ui_app.app"'

_STUB_HEADER = (
    "# GENERATED by backpropagate on every `backprop ui` launch — do not edit.\n"
    "# Rendered from the package-side template at:\n"
    "#   {template}\n"
    "# (the template's own module docstring follows below, unparsed)\n"
)


def _default_warn(message: str) -> None:
    print(message, file=sys.stderr)


class UiWorkdirCreateError(OSError):
    """The per-user UI working directory could not be created."""

    def __init__(self, workdir: Path, reason: BaseException):
        self.workdir = Path(workdir)
        super().__init__(
            f"Could not create the per-user UI working folder {self.workdir}: {reason}"
        )


def package_dir_writable(package_dir: Path) -> bool:
    """Whether the package directory can host Reflex's writes.

    Uses ``os.access`` so a read-only install (the Store layout under
    WindowsApps) is refused without creating a probe file there.
    """
    try:
        path = Path(package_dir)
        return path.is_dir() and os.access(path, os.W_OK)
    except OSError:
        return False


def _create_workdir(workdir: Path) -> None:
    try:
        workdir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise UiWorkdirCreateError(workdir, exc) from exc


def package_dir_key(package_dir: Path) -> str:
    """Stable 8-hex-char key for an install location.

    ``os.path.normcase`` folds case on Windows so two spellings of the same
    directory hash identically; it is a no-op on POSIX.
    """
    raw = os.path.normcase(str(Path(package_dir).resolve()))
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:8]


def default_ui_work_root() -> Path:
    """Base directory that holds every per-install UI working directory."""
    if sys.platform == "win32":
        local = os.environ.get("LOCALAPPDATA", "").strip()
        root = Path(local) if local else Path.home() / "AppData" / "Local"
        return root / "backpropagate" / "ui"
    cache = os.environ.get("XDG_CACHE_HOME", "").strip()
    root = Path(cache) if cache else Path.home() / ".cache"
    return root / "backpropagate" / "ui"


def render_stub_rxconfig(template_path: Path) -> str:
    """Render the working-directory stub from the package rxconfig template.

    Renders by copying the template and retargeting the single
    ``app_module_import`` anchor, so the auth guard / CORS / telemetry
    settings can never drift from the shipped configuration. A template
    without exactly one anchor is a packaging bug: raise, never guess.
    """
    text = Path(template_path).read_text(encoding="utf-8")
    count = text.count(_APP_MODULE_IMPORT_REL)
    if count != 1:
        raise RuntimeError(
            f"rxconfig template at {template_path} must contain exactly one "
            f"{_APP_MODULE_IMPORT_REL} anchor to render the working-directory "
            f"stub (found {count}). The stub is a patched copy of the shipped "
            "template; refusing to guess where a changed anchor belongs."
        )
    patched = text.replace(_APP_MODULE_IMPORT_REL, _APP_MODULE_IMPORT_ABS)
    return _STUB_HEADER.format(template=template_path) + patched


def _ensure_stub_rxconfig(package_dir: Path, workdir: Path) -> None:
    source = render_stub_rxconfig(package_dir / "rxconfig.py")
    target = workdir / "rxconfig.py"
    # Skip the write when the stub is already current: read-only-after-first-
    # launch sandboxes and identical concurrent launches both stay cheap. A
    # present-but-unreadable stub is a real problem — let that OSError surface.
    if target.is_file() and target.read_text(encoding="utf-8") == source:
        return
    target.write_text(source, encoding="utf-8")


def sync_ui_assets(package_dir: Path, workdir: Path) -> None:
    """Mirror the package's ``assets/`` (logo, icons) into the working directory.

    Reflex serves an app's static files from ``<app root>/assets`` (copied into
    ``.web/public`` at build time). Since 1.8.2 the app root is the per-user
    working directory, not the package, so without this copy every image the
    UI references (``/logo.png``, ``/icons/*.svg``) was a 404 and rendered as
    a broken image. Files are only rewritten when their size or mtime differ,
    so warm launches cost a stat per file.
    """
    source = Path(package_dir) / "assets"
    if not source.is_dir():
        return
    target = Path(workdir) / "assets"
    for src in source.rglob("*"):
        rel = src.relative_to(source)
        dst = target / rel
        if src.is_dir():
            dst.mkdir(parents=True, exist_ok=True)
            continue
        try:
            s = src.stat()
            d = dst.stat()
            if d.st_size == s.st_size and int(d.st_mtime) == int(s.st_mtime):
                continue
        except FileNotFoundError:
            pass
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)


def _prune_stale_siblings(
    base: Path, *, current: str, key: str, warn: Callable[[str], None]
) -> None:
    """Remove older ``<version>-<key>`` dirs belonging to THIS install.

    Only directories whose name ends with this install's ``-<key>`` suffix
    are touched — a coexisting pip/Store install has a different key and is
    left alone, as is anything else in the base directory.
    """
    suffix = f"-{key}"
    try:
        children = list(base.iterdir())
    except OSError:
        return
    for child in children:
        if child.name == current or not child.name.endswith(suffix):
            continue
        if not child.is_dir():
            continue
        try:
            shutil.rmtree(child)
        except OSError as exc:
            warn(f"Could not remove a stale UI working directory {child}: {exc}")


def clear_saved_ui_state(workdir: Path, warn: Callable[[str], None]) -> None:
    """Remove Reflex's saved session state (``.states/``) left by an earlier run.

    Reflex pickles each browser session's state there and keeps the files
    after the server stops. Up to 1.8.1 that state could hold a HuggingFace
    token typed into the Export page; nothing in it is needed across a
    restart (a running job is found again from its own files), so every
    launch starts from none. ``reflex run`` resets this folder itself today;
    doing it here keeps the guarantee ours rather than the framework's.
    """
    states = Path(workdir) / ".states"
    if states.is_symlink() or not states.is_dir():
        return
    try:
        shutil.rmtree(states)
    except OSError as exc:
        warn(f"Could not remove saved UI session state at {states}: {exc}")


def ensure_ui_workdir(
    package_dir: Path,
    *,
    version: str | None = None,
    warn: Callable[[str], None] | None = None,
) -> Path:
    """Create/register the per-user Reflex working directory and return it.

    ``package_dir`` is the installed ``backpropagate/`` directory (the one
    shipping the rxconfig.py template). ``version`` defaults to the installed
    backpropagate version. Raises ``OSError`` when the directory cannot be
    created and ``RuntimeError`` when the rxconfig template has drifted.
    """
    if version is None:
        from . import __version__

        version = __version__
    warn = warn or _default_warn
    package_dir = Path(package_dir).resolve()

    override = os.environ.get(WORKDIR_ENV_VAR, "").strip()
    if override:
        workdir = Path(override).expanduser()
        _create_workdir(workdir)
        clear_saved_ui_state(workdir, warn)
        _ensure_stub_rxconfig(package_dir, workdir)
        sync_ui_assets(package_dir, workdir)
        return workdir

    key = package_dir_key(package_dir)
    workdir = default_ui_work_root() / f"{version}-{key}"
    _create_workdir(workdir)
    _prune_stale_siblings(workdir.parent, current=workdir.name, key=key, warn=warn)
    clear_saved_ui_state(workdir, warn)
    _ensure_stub_rxconfig(package_dir, workdir)
    sync_ui_assets(package_dir, workdir)
    return workdir


def prepare_ui_cwd(
    package_dir: Path,
    *,
    version: str | None = None,
    warn: Callable[[str], None] | None = None,
) -> Path:
    """Return the directory ``reflex run`` should use as its cwd.

    The per-user folder wins. If it cannot be created and ``package_dir``
    is writable, return ``package_dir`` without rewriting the package's
    ``rxconfig.py`` (that template is already right when the cwd is the
    package). If the package directory is not writable, raise
    ``RUNTIME_UI_WORKDIR_UNAVAILABLE`` and do not write there.
    """
    from .exceptions import BackpropagateError

    warn = warn or _default_warn
    package_dir = Path(package_dir)
    try:
        return ensure_ui_workdir(package_dir, version=version, warn=warn)
    except UiWorkdirCreateError as exc:
        if package_dir_writable(package_dir):
            warn(
                f"Could not prepare the per-user UI working directory {exc.workdir} "
                f"({exc}); running Reflex from the package directory instead "
                "(this checkout is writable)."
            )
            return package_dir
        raise BackpropagateError(
            f"Could not create the per-user UI working folder {exc.workdir}.",
            suggestion=(
                "Choose another folder by setting BACKPROPAGATE_UI_WORKDIR to a "
                "directory your account can create. The installed package folder "
                "is not writable, so the UI will not run from it."
            ),
            code="RUNTIME_UI_WORKDIR_UNAVAILABLE",
            cause=exc,
        ) from exc
